# Generated by Django 2.2.2 on 2019-07-12 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('carrier', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('last_import', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
